sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cockochan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t cockochan/multi-client
  - docker build -t cockochan/multi-ngnix ./ngnix
  - docker build -t cockochan/multi-server ./server
  - docker build -t cockochan/multi-worker ./worker