sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cockochan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cockochan/react-test npm test

after_success:
  - docker build -t cockochan/multi-client
  - docker build -t cockochan/multi-ngnix ./ngnix
  - docker build -t cockochan/multi-server ./server
  - docker build -t cockochan/multi-worker ./worker
#Log in dokha
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
#push the images to gh
  - docker push cockochan/multi-client
  - docker push cockochan/multi-ngnix
  - docker push cockochan/multi-server
  - docker push cockochan/multi-worker
